version: '3'

services:

  metabase-db:
    container_name: metabase-db
    image: postgres:9.6
    restart: always  
    volumes:
      - "./data/metabase/pgdata:/var/lib/postgresql/data"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=metabase
      - POSTGRES_USER=metabase
      - POSTGRES_PASSWORD=metabase 

  metabase:
    container_name: metabase
    image: metabase/metabase:v0.35.4
    restart: always 
    volumes:
      - "./data/metabase/metabase-data:/metabase-data"
    ports:
      - 3000:3000
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=metabase
      - MB_DB_PASS=metabase
      - MB_DB_HOST=metabase-db
    depends_on:
      - metabase-db
    links:
      - metabase-db
