version: "3"
services:

  # image for jupyter
  # jupyter:
  #   container_name: "zihao_jupyter"
  #   image: seuphor/ds-jupyter
  #   volumes:
  #     - ./shared:/home/jovyan/shared
  #   ports:
  #     - 8888:8888

  # image for postgres
  postgres:
    container_name: "zihao_postgres"
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    logging:
        options:
            max-size: 10m
            max-file: "3"

  # image for airflow
  webserver:
    container_name: "zihao_airflow"
    image: seuphor/airflow
    restart: always
    depends_on:
        - postgres
    environment:
        - LOAD_EX=n
        - EXECUTOR=Local
    logging:
        options:
            max-size: 10m
            max-file: "3"
    volumes:
        - ./dags:/usr/local/airflow/dags
        - ./shared:/usr/local/airflow/shared
        # - ./plugins:/usr/local/airflow/plugins
    ports:
        - "8080:8080"
    command: webserver
    healthcheck:
        test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
        interval: 30s
        timeout: 30s
        retries: 3
